### ISSUE TITLE
Dataset used

### ISSUE THREAD

**Issue by jbk3407** [wonbeomjang/mobile-hair-segmentation-pytorch#12]
Hi, I'm trying to train the model you implemented.

Can you tell me what dataset you used to train this model?

thank you in advance.

**Comment by wonbeomjang** [comment]
hello.
I use lfw dataset.

**Comment by ferdyanggara** [comment]
hey please man, upload the dataset

**Comment by ferdyanggara** [comment]
i mean you can give clue on how the preprocessing done
