### ISSUE TITLE
About Pretrained model

### ISSUE THREAD

**Issue by Jackson-LIMU** [wonbeomjang/mobile-hair-segmentation-pytorch#14]
你好，可以提供下模型的预训练权重吗？

**Comment by ferdyanggara** [comment]
yo speak english pls

**Comment by ferdyanggara** [comment]
@Jackson-LIMU

**Comment by wonbeomjang** [comment]
it is in https://github.com/wonbeomjang/mobile-hair-segmentation-pytorch/releases/tag/paramter
